import React, { useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import clsx from "clsx";
import { Manrope } from "next/font/google";
import { Footer } from "@/components/Footer/Footer";
import { Converter } from "@/pages-partials/Converter";
import { Header, TabType } from "@/components/Header/Header";
import { HowItWorks } from "@/pages-partials/HowItWorks/HowItWorks";
import { ERC223 } from "@/pages-partials/ERC223/ERC223";
import { AddressBalance } from "@/pages-partials/AddressBalance/AddressBalance";

export const manrope = Manrope({ subsets: ["latin"] });

export default function Home() {
  const [tab, setTab] = useState("converter" as TabType);
  const [defaultChainId, setDefaultChainId] = useState(1);
  const [isChangeNetworkOpen, setIsChangeNetworkOpen] = useState(false);

  return (
    <>
      <Head>
        <title>ERC223 converter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={clsx(styles.main, manrope.className)}>
        <Header
          tab={tab}
          setTab={setTab}
          defaultChainId={defaultChainId}
          setDefaultChainId={setDefaultChainId}
          isChangeNetworkOpen={isChangeNetworkOpen}
          setIsChangeNetworkOpen={setIsChangeNetworkOpen}
        />
        <div className={styles.contentBlockContainer}>
          <div className={styles.contentBlock}>
            {tab === "converter" ? (
              <Converter
                defaultChainId={defaultChainId}
                setIsChangeNetworkOpen={setIsChangeNetworkOpen}
              />
            ) : null}
            {tab === "howItWorks" ? <HowItWorks /> : null}
            {tab === "ERC223" ? <ERC223 /> : null}
            {tab === "addressBalance" ? <AddressBalance defaultChainId={defaultChainId} /> : null}
          </div>
        </div>
        <Footer />
        <div id="drawer-root" />
      </div>
    </>
  );
}
