import React, { useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import clsx from "clsx";
import { Manrope } from "next/font/google";
import { Footer } from "@/components/Footer/Footer";
import { Header } from "@/components/Header/Header";
import { TokenLosses } from "@/pages-partials/TokenLosses/TokenLosses";

export const manrope = Manrope({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Losses calculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={clsx(styles.main, manrope.className)}>
        <Header />
        <div className={styles.contentBlockContainer}>
          <div className={styles.contentBlock}>
            <TokenLosses />
          </div>
        </div>
        <Footer />
        <div id="drawer-root" />
      </div>
    </>
  );
}
