import clsx from "clsx";
import { Goldman } from "next/font/google";
import Head from "next/head";
import React, { useState } from "react";

import { Footer } from "@/components/Footer/Footer";
import { Header } from "@/components/Header/Header";
import { TokenLosses } from "@/pages-partials/TokenLosses/TokenLosses";

import styles from "../styles/Home.module.scss";

export const goldman = Goldman({ subsets: ["latin"], weight: ["400", "700"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>ERC-20 Losses Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={clsx(styles.main, goldman.className)}>
        <Header />
        <div className={styles.contentBlockContainer}>
          <div className={styles.contentBlock}>
            <TokenLosses />
          </div>
        </div>
        <Footer />
        <div id="drawer-root" />
      </div>
    </>
  );
}
